# Generated by Django 5.1.7 on 2025-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='title',
            field=models.CharField(default='기본', max_length=20),
            preserve_default=False,
        ),
    ]
